### PR TITLE
multi mapping page

### PR DESCRIPTION
**Pull request by Pelsin**
Starting point, adds a route: /multi-mapping
Things that are left:

- [x] Translations keys
- [x] implement /api/getPinMappingsV2
- [x] action
- [x] customDpadMask
- [x] customButtonMask
- [x] Button labels depending on mode
- [x] Better name for api endpoints :)
- [x] ~Should it handle profiles also?~
- [ ] Backup / export
- [x] Update pin mapping after setting multi mapping

Screenshot 2024-02-14 at 02 07 52

### CODE REVIEW

**Comment by bsstephan** [comment]
@Pelsin I have updated my branch with a couple bugfixes and an implementation of `/api/getPinMappingsV2`. The payload looks like this.

```json
{
    "pin00": {
        "action": 14,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin01": {
        "action": 20,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin02": {
        "action": 0,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin03": {
        "action": 0,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin04": {
        "action": 0,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin05": {
        "action": 12,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin06": {
        "action": 11,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin07": {
        "action": 6,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin08": {
        "action": 5,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin09": {
        "action": 10,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin10": {
        "action": 9,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin11": {
        "action": 8,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin12": {
        "action": 7,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin13": {
        "action": 14,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin14": {
        "action": 15,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin15": {
        "action": 13,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin16": {
        "action": 4,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin17": {
        "action": 3,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin18": {
        "action": 1,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin19": {
        "action": 2,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin20": {
        "action": 16,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin21": {
        "action": 17,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin22": {
        "action": 18,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin23": {
        "action": 20,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin24": {
        "action": 21,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin25": {
        "action": -5,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin26": {
        "action": 22,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin27": {
        "action": 23,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin28": {
        "action": 20,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin29": {
        "action": 19,
        "customButtonMask": 0,
        "customDpadMask": 0
    }
}
```

I didn't get a chance to update `app.js` or anything yet, but this should give something to go on.

**Comment by Pelsin** [comment]
Tried in the current state saving a customButtonMask with this payload:
Screenshot 2024-02-29 at 00 49 57


```json
{
    "pin00": {
        "action": -10,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin01": {
        "action": -10,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin02": {
        "action": 33,
        "customButtonMask": 6,
        "customDpadMask": 0
    },
    "pin03": {
        "action": 2,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin04": {
        "action": 4,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin05": {
        "action": 3,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin06": {
        "action": 5,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin07": {
        "action": 6,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin08": {
        "action": 12,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin09": {
        "action": 11,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin10": {
        "action": 7,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin11": {
        "action": 8,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin12": {
        "action": 10,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin13": {
        "action": 9,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin14": {
        "action": 32,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin15": {
        "action": -10,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin16": {
        "action": 13,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin17": {
        "action": 14,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin18": {
        "action": 17,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin19": {
        "action": 18,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin20": {
        "action": 15,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin21": {
        "action": 16,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin22": {
        "action": -10,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin23": {
        "action": -10,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin24": {
        "action": -10,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin25": {
        "action": -10,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin26": {
        "action": 17,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin27": {
        "action": 1,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin28": {
        "action": 0,
        "customButtonMask": 0,
        "customDpadMask": 0
    },
    "pin29": {
        "action": -10,
        "customButtonMask": 0,
        "customDpadMask": 0
    }
}
```

Got a 200 response but it does not persist, am i sending the action incorrectly?

**Comment by bsstephan** [comment]
@Pelsin - thinko in my side of `webconfig.cpp`, should be fixed now.

While testing it (I was able to successfully use the web UI to assign a pin to B1+B2+B3, yay), it looked like the Up/Down/Left/Right selections in the field weren't adding to `customDpadMask` and were instead just making impossibly large `customButtonMask` values. But the buttons (or at least the ones I tested) seemed to work fine. We're getting there!

**Comment by Pelsin** [comment]
@bsstephan Nice!
Yeah i'm reusing the buttonMask structure in the hotkeys atm. it seems we are just sending one mask including the buttonMask and dPad if i understand it correctly: https://github.com/bsstephan/GP2040-CE/blob/one-pin-multiple-buttons/src/configs/webconfig.cpp#L311

Just need to do some small changes on the frontend so that hotkeys and multi mapping can use the same data

**Comment by Pelsin** [comment]
@bsstephan We should now be in a good enough state i think!

**Comment by bsstephan** [comment]
Looks and works great! I'm going to try one hack for the profiles as we discussed, but otherwise I think this is ready for a PR against the main repo. Thanks so much!

**Pull request merged**
